export const SET_ACTIVE_MENU = 'SET_ACTIVE_MENU'
export const REPOSITION_CATEGORY = 'REPOSITION_CATEGORY'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const TOGGLE_ONLINE = 'TOGGLE_ONLINE'
export const SET_SERVER_MODE = 'SET_SERVER_MODE'
export const CLOSE_MESSAGE_DIALOG = 'CLOSE_MESSAGE_DIALOG'
export const UPDATE_MAP_CENTER = 'UPDATE_MAP_CENTER'
